version: '3.3'

services:
  postgres:
    image: postgres:14.3
    restart: always
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
    container_name: bot_db
    volumes:
      - ./postgres:/var/lib/postgresql/data
